---

#################################################################

- name: "apt | update cache"
  apt:
    update_cache: yes

- name: "apt | install"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items: 
    - "{{ libraries_apt }}"
    - "{{ packages_apt  }}"

#- name: "apt | autoclean"
#  apt:
#    autoclean : yes     # req ansible min 2.4
#    autoremove: yes     # req ansible min 2.1
#
#################################################################

