syntax on
filetype plugin indent on
set backspace=indent,eol,start
set autoindent
set ts=2
set shiftwidth=2
set expandtab
set nocompatible
set number
set showmatch
set hlsearch
set incsearch
set clipboard=unnamed
set noswapfile

set pastetoggle=<F2>

let mapleader =","

map <silent> <leader><space> :nohl<cr>

nmap <F1> :echo<cr>
imap <F1> <C-o>:echo<cr>
nnoremap <silent> <F1> :NERDTreeToggle<cr>
