---

- hosts         : localhost
  become        : yes
  become_method : sudo
  connection    : local
  gather_facts  : yes

  vars:
    - gui       : False
      proxy     : False

      root_user:
        id      : 'root'
        home    : '/root'
        name    : 'root'
        email   : 'root@root.com'

      primary_user:
        id      : 'ubuntu'
        home    : '/home/ubuntu'
        name    : 'Piotrek'
        email   : 'kapitanpiotrek@gmail.com'

      all_users:
        - '{{ root_user }}'
        - '{{ primary_user }}'

  pre_tasks:
    - debug:
        msg: "Distribution: {{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
    - debug:
        msg: "VM Status   : {{ ansible_virtualization_role }} [{{ ansible_virtualization_type }}]"

  roles:
    - { role: prereq                          }
    - { role: git                             }
    - { role: bash                            }
    - { role: vim                             }
#   - { role: powerline-shell                 }
#   - { role: java                            }
#   - { role: general                         }
#   - { role: keychain                        }
#   - { role: wallpaper                       }
#   - { role: system-monitor                  }
#   - { role: google-chrome                   }
#   - { role: terminator                      }
#   - { role: developer/general               }
#   - { role: developer/vvtomcat              }
#   - { role: developer/intellij              ,
#         intellij_year       : "2017.3"      ,
#         intellij_subversion : "2"           }
#   - { role: developer/android               ,
#         android_version     : "3.0.1.0"     ,
#         android_build       : "171.4443003" }
#   - { role: developer/gradle                }
    - { role: developer/terraform             }
#   - { role: developer/docker                }
    - { role: developer/awscli                }
#   - { role: media/steam                     }
    - { role: work/forticlient                }
